server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service


  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE-0
          predicates:
            - Path=/user-service/**
        - id: catalog-service
          uri: lb://CATALOG-SERVICE-0
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE-0
          predicates:
            - Path=/order-service/**
        - id: first-service
#          uri: lb://USER-SERVICE-8081
          uri: lb://USER-SERVICE-0
          predicates:
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=request, request-first-value-yaml
#            - AddResponseHeader=response, response-first-value-yaml
            - CustomFilter
        - id: second-service
          uri: lb://USER-SERVICE-8082
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=request, request-second-value-yaml
#            - AddResponseHeader=response, response-second-value-yaml
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, Logging Filter
                preLogger: true
                postLogger: true